import {RFValue} from 'react-native-responsive-fontsize';
import {Platform} from 'react-native';
const valFontFlag = Platform.OS === 'android' ? 0 : 0;

const Theme = {
  colors: {
    appColor: '#000000',
    appBgColor: '#EFF3F6',
    white: '#FFFFFF',
    black: '#000000',
    textColor1: '#747474',
    appGreen: '#00B724',
    appPurple: '#8669FF',
    appRed: '#FF4646',
    appGray1: '#747474',
    appGray: '#9B9B9B',
    appLink: '#007AFF',
    navigation: '#f3f3f3',
    buttonBorderColor: '#DEDEDE',
  },
  fontFamily: {
    fontSFProSemiBold: 'SFProDisplay-Semibold',
    fontSFProRegular: 'SFProDisplay-Regular',
    fontSFProMedium: 'SFProDisplay-Medium',
    fontSFProBold: 'SFProDisplay-Bold',
  },
  fontSize: {
    size10: RFValue(10 - valFontFlag),
    size11: RFValue(11 - valFontFlag),
    size12: RFValue(12 - valFontFlag),
    size13: RFValue(13 - valFontFlag),
    size15: RFValue(15 - valFontFlag),
    size16: RFValue(16 - valFontFlag),
    size18: RFValue(18 - valFontFlag),
    size20: RFValue(20 - valFontFlag),
    size22: RFValue(22 - valFontFlag),
    size25: RFValue(25 - valFontFlag),
    size28: RFValue(28 - valFontFlag),
    size30: RFValue(30 - valFontFlag),
    size32: RFValue(32 - valFontFlag),
    size35: RFValue(35 - valFontFlag),
    size38: RFValue(38 - valFontFlag),
    size40: RFValue(40 - valFontFlag),
    size42: RFValue(42 - valFontFlag),
    size45: RFValue(45 - valFontFlag),
    size48: RFValue(48 - valFontFlag),
    size50: RFValue(50 - valFontFlag),
    size60: RFValue(60 - valFontFlag),
    size80: RFValue(80 - valFontFlag),
  },
  icons: {
    ic_today_selected: require('../resources/images/ic_today_selected.png'),
    ic_today_unselected: require('../resources/images/ic_today_unselected.png'),
    ic_tasks_selected: require('../resources/images/ic_tasks_selected.png'),
    ic_tasks_unselected: require('../resources/images/ic_tasks_unselected.png'),
    ic_settings_selected: require('../resources/images/ic_settings_selected.png'),
    ic_settings_unselected: require('../resources/images/ic_settings_unselected.png'),
    ic_menu_drawer: require('../resources/images/ic_menu_drawer_open.png'),
    ic_close_drawer: require('../resources/images/ic_menu_drawer_close.png'),
    ic_icon_drawer: require('../resources/images/ic_tasks_selected.png'),
    ic_item_checked: require('../resources/images/ic_item_checked.png'),
    ic_item_unchecked: require('../resources/images/ic_item_unchecked.png'),
    ic_all_tasks: require('../resources/images/ic_all_tasks.png'),
    ic_personal_tasks: require('../resources/images/ic_personal_tasks.png'),
    ic_work_tasks: require('../resources/images/ic_work_tasks.png'),
    ic_health_tasks: require('../resources/images/ic_health_tasks.png'),
    ic_other_tasks: require('../resources/images/ic_other_tasks.png'),
    ic_add_tasks: require('../resources/images/ic_add_tasks.png'),
  },
};

export default Theme;
