export const StaticData = [
  {
    id: 1,
    title: 'Consectetur qui anim consequat in.',
    date: '05-07-2021',
    time: '11:00:00',
    type: 'Personal',
    isChecked: false,
  },
  {
    id: 2,
    title: 'Labore magna minim et minim.',
    date: '05-07-2021',
    time: '12:00:00',
    type: 'Work',
    isChecked: false,
  },
  {
    id: 3,
    title: 'Mollit ut eiusmod nisi cupidatat veniam.',
    date: '05-07-2021',
    time: '13:00:00',
    type: 'Health',
    isChecked: false,
  },
  {
    id: 4,
    title: 'Aute dolore ea nostrud quis pariatur cupidatat cupidatat.',
    date: '05-07-2021',
    time: '14:00:00',
    type: 'Other',
    isChecked: false,
  },
  {
    id: 5,
    title: 'In anim ipsum culpa ea ut.',
    date: '06-07-2021',
    time: '15:00:00',
    type: 'Personal',
    isChecked: false,
  },
  {
    id: 6,
    title: 'Minim aute amet anim aliquip ullamco cillum non.',
    date: '05-07-2021',
    time: '16:00:00',
    type: 'Personal',
    isChecked: false,
  },
  {
    id: 7,
    title: 'Commodo non commodo esse deserunt excepteur.',
    date: '06-07-2021',
    time: '17:00:00',
    type: 'Work',
    isChecked: false,
  },
  {
    id: 8,
    title: 'Ullamco ut qui ex laborum mollit sunt nostrud sunt.',
    date: '05-07-2021',
    time: '18:00:00',
    type: 'Work',
    isChecked: false,
  },
  {
    id: 9,
    title: 'Quis tempor deserunt magna velit nostrud irure.',
    date: '05-07-2021',
    time: '19:00:00',
    type: 'Health',
    isChecked: false,
  },
  {
    id: 10,
    title: 'Proident eu incididunt aliqua fugiat ea.',
    date: '06-07-2021',
    time: '20:00:00',
    type: 'Other',
    isChecked: false,
  },
  {
    id: 11,
    title: 'Velit mollit mollit sit et sunt.',
    date: '06-07-2021',
    time: '21:00:00',
    type: 'Health',
    isChecked: false,
  },
  {
    id: 12,
    title: 'Ea id ex eu eiusmod.',
    date: '06-07-2021',
    time: '22:00:00',
    type: 'Other',
    isChecked: false,
  },
  {
    id: 13,
    title: 'Consectetur qui anim consequat in.',
    date: '05-07-2021',
    time: '11:00:00',
    type: 'Personal',
    isChecked: false,
  },
  {
    id: 14,
    title: 'Labore magna minim et minim.',
    date: '05-07-2021',
    time: '12:00:00',
    type: 'Work',
    isChecked: false,
  },
  {
    id: 15,
    title: 'Mollit ut eiusmod nisi cupidatat veniam.',
    date: '05-07-2021',
    time: '13:00:00',
    type: 'Health',
    isChecked: false,
  },
  {
    id: 16,
    title: 'Aute dolore ea nostrud quis pariatur cupidatat cupidatat.',
    date: '05-07-2021',
    time: '14:00:00',
    type: 'Other',
    isChecked: false,
  },
  {
    id: 17,
    title: 'In anim ipsum culpa ea ut.',
    date: '05-07-2021',
    time: '15:00:00',
    type: 'Personal',
    isChecked: false,
  },
  {
    id: 18,
    title: 'Minim aute amet anim aliquip ullamco cillum non.',
    date: '05-07-2021',
    time: '16:00:00',
    type: 'Personal',
    isChecked: false,
  },
  {
    id: 19,
    title: 'Commodo non commodo esse deserunt excepteur.',
    date: '06-07-2021',
    time: '17:00:00',
    type: 'Work',
    isChecked: false,
  },
  {
    id: 20,
    title: 'Ullamco ut qui ex laborum mollit sunt nostrud sunt.',
    date: '05-07-2021',
    time: '18:00:00',
    type: 'Work',
    isChecked: false,
  },
  {
    id: 21,
    title: 'Quis tempor deserunt magna velit nostrud irure.',
    date: '05-07-2021',
    time: '19:00:00',
    type: 'Health',
    isChecked: false,
  },
  {
    id: 22,
    title: 'Proident eu incididunt aliqua fugiat ea.',
    date: '06-07-2021',
    time: '20:00:00',
    type: 'Other',
    isChecked: false,
  },
  {
    id: 23,
    title: 'Velit mollit mollit sit et sunt.',
    date: '06-07-2021',
    time: '21:00:00',
    type: 'Health',
    isChecked: false,
  },
  {
    id: 24,
    title: 'Ea id ex eu eiusmod.',
    date: '06-07-2021',
    time: '22:00:00',
    type: 'Other',
    isChecked: false,
  },
];
